### ISSUE TITLE
Stem short vowel deletion

### ISSUE THREAD

**Issue by zrailing** [zrailing/cro-morph#2]
According to Grazcyk, stem-final short vowels are deleted at the morpheme boundary, unless a three-consonant cluster or nasal plus voiceless obstruent cluster would result. 

E.g. 
- dáaka "child" + bacheé "man" = dáakbachee "son"
- úuxa "deer" + dáaka = úuxdaaka "fawn"
- ishtá "eye" + kísshi "imitation" = ishtakísshi "eyeglasses (*ishtkísshi)
- kala "already" + koolúu "be there"  = kalakoolúu (*kankoolúu)

In trying to capture this in the `twol` file I struggled with trying to use a set on the underlying form, which didn't seem to work, or the regular `[this | that | the other thing]` approach on the underlying form, which didn't seem to work either. I feel like maybe the way to go here would be an archimorpheme but I'm struggling somewhat with whether or not that's the right choice to run with as you'd have to include that on any base form that has a stem-final short vowel, meaning a, á, i, í, u, ú.

**Comment by ftyers** [comment]
So, the rule is:

Delete, unless:
* three consonant cluster (on either side of the boundary)
* nasal + voiceless obstruent

So, something like:

```
"Stem short vowel deletion"
Vx:0 <=> _ %>: ; 
   except 
        [ :Cns :Cns ] _ %>: :Cns ;
                :Cns  _ %>: [ :Cns :Cns ] ;
               :Nasal _ %>: :VoicelessObs ; 
```

It would be helpful to have some examples of the pair strings that should be accepted/rejected.
